[2025-03-09T16:20:30.550+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: openweather_data_lake.initialize_buckets scheduled__2025-03-08T16:20:15.319377+00:00 [queued]>
[2025-03-09T16:20:30.562+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: openweather_data_lake.initialize_buckets scheduled__2025-03-08T16:20:15.319377+00:00 [queued]>
[2025-03-09T16:20:30.562+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2025-03-09T16:20:30.579+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): initialize_buckets> on 2025-03-08 16:20:15.319377+00:00
[2025-03-09T16:20:30.607+0000] {standard_task_runner.py:57} INFO - Started process 2577 to run task
[2025-03-09T16:20:30.645+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'openweather_data_lake', 'initialize_buckets', 'scheduled__2025-03-08T16:20:15.319377+00:00', '--job-id', '436', '--raw', '--subdir', 'DAGS_FOLDER/openweather_data_lake.py', '--cfg-path', '/tmp/tmpm9pzdgz4']
[2025-03-09T16:20:30.664+0000] {standard_task_runner.py:85} INFO - Job 436: Subtask initialize_buckets
[2025-03-09T16:20:30.732+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-09T16:20:30.824+0000] {task_command.py:415} INFO - Running <TaskInstance: openweather_data_lake.initialize_buckets scheduled__2025-03-08T16:20:15.319377+00:00 [running]> on host 405dcb727823
[2025-03-09T16:20:30.958+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='openweather_data_lake' AIRFLOW_CTX_TASK_ID='initialize_buckets' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T16:20:15.319377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T16:20:15.319377+00:00'
[2025-03-09T16:20:31.776+0000] {logging_mixin.py:151} INFO - [INFO] Bucket 'raw' already exists.
[2025-03-09T16:20:31.780+0000] {logging_mixin.py:151} INFO - [INFO] Bucket 'staging' already exists.
[2025-03-09T16:20:31.780+0000] {logging_mixin.py:151} INFO - [INFO] Bucket 'curated' already exists.
[2025-03-09T16:20:31.781+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-09T16:20:31.799+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=openweather_data_lake, task_id=initialize_buckets, execution_date=20250308T162015, start_date=20250309T162030, end_date=20250309T162031
[2025-03-09T16:20:31.851+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-09T16:20:31.935+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
